### ISSUE TITLE
Is this cross-platform?

### ISSUE THREAD

**Issue by styfle** [sol-prog/cpp17-filewatcher#1]
Node.js has a file watcher but it has many [caveats](https://nodejs.org/docs/latest/api/fs.html#fs_caveats) when recursively watching directories.

Does this code work recursively on Mac, Linux, Windows without any dependencies/caveats?

**Comment by sol-prog** [comment]
The code needs a C++17 compiler, otherwise it should work on Mac, Linux and Windows.

However, I don't advise of using it in production. If you want performance, you should use the operating system functions directly (e.g. inotify on Linux).
